/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2025-01-30 13:04:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AboutUs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Navbar.jsp", Long.valueOf(1703083598016L));
    _jspx_dependants.put("/Footer.jsp", Long.valueOf(1703090351632L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <!--Bootstrap link-->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!--Javascript link-->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <!--CSS file-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"Style.css\">\r\n");
      out.write("    <title>About Us</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!--Navbar Start-->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-sm bg-dark navbar-dark sticky-top\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("                <img src=\"\" alt=\"\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapsibleNavbar\">\r\n");
      out.write("              <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse justify-content-end \" id=\"collapsiblenavbar\">\r\n");
      out.write("                <ul class=\"navbar-nav d-flex\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"index.jsp\" class=\"nav-link\">HOME</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"AboutUs.jsp\" class=\"nav-link\">ABOUT US</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"notice.jsp\" class=\"nav-link\">NOTICES</a>\r\n");
      out.write("                    </li>                                     \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"Registration.jsp\" class=\"nav-link\">REGISTRATION</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!--Navbar End-->");
      out.write("\r\n");
      out.write("<!--About Us Start-->\r\n");
      out.write("    <section id=\"AboutUs\">\r\n");
      out.write("    	<div class=\"container pb-3 shadow-lg\">\r\n");
      out.write("        <h2 class=\"text-center mt-5\"><span class=\"Main-heading\">&#10022 ABOUT US &#10022</span></h2>\r\n");
      out.write("        <div class=\"row my-4\">\r\n");
      out.write("            <div class=\"col-md-5 px-5 offset-md-1 pt-4\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <img src=\"dyimage.jpeg\" alt=\"About-Us\" height=\"100%\" width=\"100%\" class=\"img-responsive\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-5 pt-4\">\r\n");
      out.write("                <div class=\"text-center\">Since 1983, D Y Patil Group of Institutions is leading group known amongst the top education institutions in India. The D Y Patil University, Pune was established by and under the Government of Maharashtra Act No. VI of 2019 and recognized by UGC, New Delhi, India\r\n");
      out.write("\r\n");
      out.write("                D Y Patil Group of Institutions is founded to provide quality education and contribute towards the social responsibility. The foundation was laid by Father Founder Honâble Dr D Y Patil in the year 1983 by starting the first engineering college in Navi Mumbai. Group began to grow exponentially in all the fields of education namely, Agriculture, Medical, Science, Engineering, Management, Design and many more. Under the leadership of father founder Padma Shri Dr D Y Patil group has more 12 campuses across India those includes 6 Universities and more than 150 Institutes which are engaged in delivering education from KG to PG.</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--AboutÂ UsÂ End-->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!--Footer Start-->\r\n");
      out.write("    <div class=\"container-fluid mobile-footer footer\" style=\"background-color: #1A1A1A;\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row pt-4 text-center text-light\">\r\n");
      out.write("                <div class=\"col-md-4 px-2 py-3 \">\r\n");
      out.write("                    <i class=\"fa-solid fa-house\"></i>\r\n");
      out.write("                    <div class=\"mx-3\">&#xf965</div>\r\n");
      out.write("                    <div class=\"mx-3 \">A/P:- lohegoan, Tal:- Pune, Dist:- Pune, Pin:- 413110</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4  px-2 py-3\">\r\n");
      out.write("                    <i class=\"fa-solid fa-phone\"></i>\r\n");
      out.write("                    <div class=\"mx-3\">&#9743</div>\r\n");
      out.write("                    <div class=\"mx-3\">+91 9322275614</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4 px-2 py-3\">\r\n");
      out.write("                    <i class=\"fa-solid fa-envelope\"></i>\r\n");
      out.write("                    <div class=\"mx-3 \">&#9993</div>\r\n");
      out.write("                    <div class=\"mx-3\">Dypatilmca81@gmail.com</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"text-center text-light pb-2\">\r\n");
      out.write("                <p>\r\n");
      out.write("                    &#169 All rights are reserved.\r\n");
      out.write("                </p>\r\n");
      out.write("                <p>\r\n");
      out.write("                    Design & Developed by Avinash Jaypatre\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--Footer End-->");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
