/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2025-01-30 13:04:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class Registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Navbar.jsp", Long.valueOf(1703083598016L));
    _jspx_dependants.put("/Footer.jsp", Long.valueOf(1703090351632L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <!--Bootstrap link-->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!--Javascript link-->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <!--CSS file-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"Style.css\">\r\n");
      out.write("    <title>Registration Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!--Navbar Start-->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-sm bg-dark navbar-dark sticky-top\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("                <img src=\"\" alt=\"\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapsibleNavbar\">\r\n");
      out.write("              <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse justify-content-end \" id=\"collapsiblenavbar\">\r\n");
      out.write("                <ul class=\"navbar-nav d-flex\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"index.jsp\" class=\"nav-link\">HOME</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"AboutUs.jsp\" class=\"nav-link\">ABOUT US</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"notice.jsp\" class=\"nav-link\">NOTICES</a>\r\n");
      out.write("                    </li>                                     \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"Registration.jsp\" class=\"nav-link\">REGISTRATION</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!--Navbar End-->");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row pt-2\">\r\n");
      out.write("            <div class=\"col-md-6 offset-md-3 pt-3 border border-dark rounded-3\">\r\n");
      out.write("                <h2 class=\"text-center mb-3\"><span class=\"Main-heading\">&#10022 REGISTRATION PAGE  &#10022</span></h2>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <form action=\"\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" name=\"Fname\" placeholder=\"First Name\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" name=\"Lname\" placeholder=\"Last Name\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <input type=\"email\" class=\"form-control my-2 \" name=\"Email\" placeholder=\"Enter an Email\" required>\r\n");
      out.write("                        <input type=\"number\" class=\"form-control\" name=\"Mobile\" placeholder=\"Enter Mobile Number\" required>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control my-2\" name=\"Address\" placeholder=\"Enter Address\" required>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" name=\"Password\" placeholder=\"Enter Password\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" name=\"Cpassword\" placeholder=\"Confirm Password\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div> \r\n");
      out.write("                        <div class=\"row my-2\">\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <select name=\"Uquestion\" id=\"\" class=\"form-control\" required>\r\n");
      out.write("                                    <option value=\"\" selected disabled>Select any security question</option>\r\n");
      out.write("                                    <option value=\"What is your favourite book\">What is your favourite book</option>\r\n");
      out.write("                                    <option value=\"What is your favourite actor\">What is your favourite actor</option>\r\n");
      out.write("                                    <option value=\"What is your school name\">What is your school name</option>\r\n");
      out.write("                                    <option value=\"What is your favourite sport\">What is your favourite sport</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" name=\"Uanswer\" placeholder=\"Answer\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div> \r\n");
      out.write("                        <div class=\"text-center my-3\">\r\n");
      out.write("                            <input type=\"submit\" class=\"btn btn-outline-success\" name=\"submit\" value=\"REGISTER\" required >\r\n");
      out.write("                        </div>   \r\n");
      out.write("                        <div class=\"text-center mb-4\">\r\n");
      out.write("                            <a href=\"LoginPage.jsp\" class=\"link text-success\">Already have an account?</a>\r\n");
      out.write("                        </div>                    \r\n");
      out.write("                    </form>\r\n");
      out.write("                    <!-- Database Code start -->\r\n");
      out.write("                    ");

                    	String Fname = request.getParameter("Fname");
                    	String Lname = request.getParameter("Lname");
                    	String Email = request.getParameter("Email");
                    	String Mobile = request.getParameter("Mobile");
                    	String Address = request.getParameter("Address");
                    	String Password = request.getParameter("Password");
                    	String Cpassword = request.getParameter("Cpassword");
                    	String Uquestion = request.getParameter("Uquestion");
                    	String Uanswer = request.getParameter("Uanswer");
                    	
                     	String x = request.getParameter("submit");
                     	if(x!=null && x.equals("REGISTER"))
                     	{
         	          	 	String url = "jdbc:mysql://localhost:3306?user=root&password=root";
       
                    	 	try
                    	 	{
                    	 		Class.forName("com.mysql.jdbc.Driver");
                    	 		Connection con = DriverManager.getConnection(url);
                    	 		
                    	 		String query = "insert into ragistration.newragistration(Fname,Lname,Email,Mobile,Address,Password,Cpassword,Uquestion,Uanswer) values(?,?,?,?,?,?,?,?,?)";
                    	 		
                    	 		PreparedStatement pstmt = con.prepareStatement(query);
                    	 		pstmt.setString(1,Fname);
                    	 		pstmt.setString(2,Lname);
                    	 		pstmt.setString(3,Email);
                    	 		pstmt.setString(4,Mobile);
                    	 		pstmt.setString(5,Address);
                    	 		pstmt.setString(6,Password);
                    	 		pstmt.setString(7,Cpassword);
                    	 		pstmt.setString(8,Uquestion);
                    	 		pstmt.setString(9,Uanswer);
                    	 		pstmt.executeUpdate();
                    	 		System.out.println("Data entered....");
                    	 	}
                    	 	catch(Exception e)
                    	 	{
                    	 		e.printStackTrace();
                    	 		System.out.println("Exception handled....!");
                    	 	}
                     	}
                    
      out.write("\r\n");
      out.write("                    <!-- Database Code End -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!--Footer Start-->\r\n");
      out.write("    <div class=\"container-fluid mobile-footer footer\" style=\"background-color: #1A1A1A;\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row pt-4 text-center text-light\">\r\n");
      out.write("                <div class=\"col-md-4 px-2 py-3 \">\r\n");
      out.write("                    <i class=\"fa-solid fa-house\"></i>\r\n");
      out.write("                    <div class=\"mx-3\">&#xf965</div>\r\n");
      out.write("                    <div class=\"mx-3 \">A/P:- lohegoan, Tal:- Pune, Dist:- Pune, Pin:- 413110</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4  px-2 py-3\">\r\n");
      out.write("                    <i class=\"fa-solid fa-phone\"></i>\r\n");
      out.write("                    <div class=\"mx-3\">&#9743</div>\r\n");
      out.write("                    <div class=\"mx-3\">+91 9322275614</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4 px-2 py-3\">\r\n");
      out.write("                    <i class=\"fa-solid fa-envelope\"></i>\r\n");
      out.write("                    <div class=\"mx-3 \">&#9993</div>\r\n");
      out.write("                    <div class=\"mx-3\">Dypatilmca81@gmail.com</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"text-center text-light pb-2\">\r\n");
      out.write("                <p>\r\n");
      out.write("                    &#169 All rights are reserved.\r\n");
      out.write("                </p>\r\n");
      out.write("                <p>\r\n");
      out.write("                    Design & Developed by Avinash Jaypatre\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--Footer End-->");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
